# frozen_string_literal: true

#
# ASPIRATIONAL DSL — this file does not run and cannot yet. Magik is spec only
# as of 2026-08-26: `action` is not a method that exists, and loading this file
# would raise NoMethodError. See dummy/README.md.
#
# app/actions/record_payment.rb  <->  action :record_payment
#
# The money path. Called from two places that must behave identically: the
# modal in app/screens/invoices.rb, and the Stripe webhook in
# app/api/webhooks.rb. One action, one set of invariants, two callers — which is
# why the invariants are here and not in either caller.
#
# Demonstrates: idempotent_by against an external key, a double-entry ledger
# post (Phase 5), a state transition, and a broadcast.

action :record_payment do
  params do
    field :invoice_id,      :uuid,  required: true
    field :amount,          :money, required: true
    field :method,          :enum,  values: %i[card sepa_debit bank_transfer credit_note]
    field :processor_token, :string, required: true
    # Supplied by the processor when a webhook calls this, generated by the form
    # when a human does. Either way the dedupe key is the caller's, not ours.
    field :idempotency_key, :string, required: true
  end

  idempotent_by ->(params) { params[:idempotency_key] }

  authorize { |user, _| user.can?(:record_payment) }

  perform do |params|
    invoice = Invoice.find(params[:invoice_id])

    guard "payment exceeds the outstanding balance",
          code: "LEDGERLINE_OVERPAYMENT" do
      params[:amount] <= invoice.balance
    end

    transaction do
      payment = Payment.create!(
        invoice: invoice,
        amount: params[:amount],
        method: params[:method],
        status: :settled,
        received_at: Time.now,
        processor_token: params[:processor_token],
        idempotency_key: params[:idempotency_key]
      )

      # Double entry. Debits and credits must balance or the entry is refused —
      # see app/ledgers/receivables.rb.
      Receivables.record(:payment_received, invoice: invoice, payment: payment)

      invoice.update!(status: :paid) if invoice.balance.zero?
    end

    broadcast "invoices:tenant", :paid, id: invoice.id, balance: invoice.balance
  end
end
